import {
  fetchTranscript,
  listLanguages,
  YoutubeTranscriptDisabledError,
  YoutubeTranscriptNotAvailableError,
  YoutubeTranscriptTooManyRequestError,
  YoutubeTranscriptVideoUnavailableError,
  type CaptionTrackInfo,
  type TranscriptSegment,
  type VideoDetails,
} from "youtube-transcript-plus";
import { TranscriptCacheRepository, TranscriptRepository } from "@/lib/db/repository";
import {
  storedSegmentsToTranscriptApi,
  transcriptApiSegmentsToStored,
} from "@/lib/transcript-segments";
import { extractVideoId } from "@/lib/utils";

const NO_CAPTIONS_MESSAGE = "Transcript not available for this video";
const TEMPORARY_UNAVAILABLE_MESSAGE =
  "Transcript temporarily unavailable. Try again later.";
const PLUS_FETCH_OPTIONS = { retries: 3, retryDelay: 1000 } as const;

export interface TranscriptApiSegment {
  text: string;
  start: number;
  duration: number;
}

export interface TranscriptApiMetadata {
  title?: string;
  author_name?: string;
  author_url?: string;
  thumbnail_url?: string;
}

export interface TranscriptApiResponse {
  video_id: string;
  language: string;
  transcript: TranscriptApiSegment[];
  metadata?: TranscriptApiMetadata;
}

export interface FetchTranscriptOptions {
  language?: string;
  sendMetadata?: boolean;
}

export class TranscriptRetryableError extends Error {
  constructor(message: string = TEMPORARY_UNAVAILABLE_MESSAGE) {
    super(message);
    this.name = "TranscriptRetryableError";
  }
}

function decodeHtmlEntities(text: string): string {
  const named: Record<string, string> = {
    "&amp;": "&",
    "&lt;": "<",
    "&gt;": ">",
    "&quot;": '"',
    "&apos;": "'",
    "&#39;": "'",
    "&nbsp;": " ",
  };
  const once = (value: string) =>
    value
      .replace(/&(?:amp|lt|gt|quot|apos|nbsp|#39);/g, (match) => named[match] ?? match)
      .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(parseInt(code, 10)))
      .replace(/&#x([0-9a-fA-F]+);/g, (_, code) => String.fromCharCode(parseInt(code, 16)));

  let decoded = text;
  let prev = "";
  while (prev !== decoded) {
    prev = decoded;
    decoded = once(decoded);
  }
  return decoded;
}

function normalizeVideoId(videoUrlOrId: string): string {
  return extractVideoId(videoUrlOrId) ?? videoUrlOrId;
}

function matchesLanguagePrefix(languageCode: string, prefix: string): boolean {
  const code = languageCode.toLowerCase();
  const needle = prefix.toLowerCase();
  return code === needle || code.startsWith(`${needle}-`);
}

export function pickCaptionTrack(
  tracks: CaptionTrackInfo[],
  preferred?: string,
): CaptionTrackInfo | null {
  if (tracks.length === 0) {
    return null;
  }

  const preferredCode = preferred?.trim().toLowerCase();
  const fallbacks = ["en", "id"].filter((code) => code !== preferredCode);

  if (preferredCode) {
    const humanPreferred = tracks.find(
      (track) => !track.isAutoGenerated && matchesLanguagePrefix(track.languageCode, preferredCode),
    );
    if (humanPreferred) {
      return humanPreferred;
    }

    const asrPreferred = tracks.find(
      (track) => track.isAutoGenerated && matchesLanguagePrefix(track.languageCode, preferredCode),
    );
    if (asrPreferred) {
      return asrPreferred;
    }
  }

  for (const code of fallbacks) {
    const human = tracks.find(
      (track) => !track.isAutoGenerated && matchesLanguagePrefix(track.languageCode, code),
    );
    if (human) {
      return human;
    }
  }

  for (const code of fallbacks) {
    const asr = tracks.find(
      (track) => track.isAutoGenerated && matchesLanguagePrefix(track.languageCode, code),
    );
    if (asr) {
      return asr;
    }
  }

  return tracks.find((track) => track.isAutoGenerated) ?? null;
}

function mapSegments(segments: TranscriptSegment[]): TranscriptApiSegment[] {
  return segments.map((segment) => ({
    text: decodeHtmlEntities(segment.text),
    start: segment.offset,
    duration: segment.duration,
  }));
}

function mapVideoDetails(details?: VideoDetails): TranscriptApiMetadata | undefined {
  if (!details) {
    return undefined;
  }

  const thumbnail = details.thumbnails?.at(-1)?.url ?? details.thumbnails?.[0]?.url;

  return {
    title: details.title,
    author_name: details.author,
    thumbnail_url: thumbnail,
  };
}

async function getCachedTranscriptResponse(
  videoId: string,
): Promise<TranscriptApiResponse | null> {
  const cached = await TranscriptCacheRepository.get(videoId);
  if (cached?.response?.transcript?.length) {
    return cached.response;
  }

  const storedSegments = await TranscriptRepository.getByVideoId(videoId);
  if (storedSegments.length === 0) {
    return null;
  }

  const response = storedSegmentsToTranscriptApi(
    videoId,
    storedSegments.map((segment) => ({
      start: segment.start,
      end: segment.end,
      text: segment.text,
      isChapterStart: segment.isChapterStart,
    })),
  );
  await TranscriptCacheRepository.saveResponse(videoId, response);
  return response;
}

async function cacheTranscriptResponse(
  videoId: string,
  response: TranscriptApiResponse,
): Promise<void> {
  await TranscriptCacheRepository.saveResponse(videoId, response);
  await TranscriptRepository.upsertSegments(
    videoId,
    transcriptApiSegmentsToStored(response.transcript),
  );
}

export async function fetchTranscriptResponse(
  videoUrlOrId: string,
  options: FetchTranscriptOptions = {},
): Promise<TranscriptApiResponse> {
  const videoId = normalizeVideoId(videoUrlOrId);
  const cached = await getCachedTranscriptResponse(videoId);
  if (cached) {
    return cached;
  }

  let tracks: CaptionTrackInfo[];
  try {
    tracks = await listLanguages(videoId, PLUS_FETCH_OPTIONS);
  } catch (error) {
    if (error instanceof YoutubeTranscriptDisabledError) {
      await TranscriptCacheRepository.markUnavailable(videoId);
      throw new Error(NO_CAPTIONS_MESSAGE);
    }
    if (
      error instanceof YoutubeTranscriptTooManyRequestError ||
      error instanceof YoutubeTranscriptNotAvailableError ||
      error instanceof YoutubeTranscriptVideoUnavailableError
    ) {
      throw new TranscriptRetryableError();
    }
    throw error;
  }

  const track = pickCaptionTrack(tracks, options.language);
  if (!track) {
    await TranscriptCacheRepository.markUnavailable(videoId);
    throw new Error(NO_CAPTIONS_MESSAGE);
  }

  try {
    const fetched = await fetchTranscript(videoId, {
      ...PLUS_FETCH_OPTIONS,
      lang: track.languageCode,
      videoDetails: true,
    });

    const mapped = mapSegments(fetched.segments);
    if (mapped.length === 0) {
      throw new TranscriptRetryableError();
    }

    const metadata = options.sendMetadata === true
      ? mapVideoDetails(fetched.videoDetails)
      : undefined;

    const response: TranscriptApiResponse = {
      video_id: videoId,
      language: track.languageCode,
      transcript: mapped,
      metadata,
    };

    await cacheTranscriptResponse(videoId, response);
    return response;
  } catch (error) {
    if (error instanceof TranscriptRetryableError) {
      throw error;
    }
    if (error instanceof YoutubeTranscriptTooManyRequestError) {
      throw new TranscriptRetryableError();
    }
    if (error instanceof YoutubeTranscriptDisabledError) {
      await TranscriptCacheRepository.markUnavailable(videoId);
      throw new Error(NO_CAPTIONS_MESSAGE);
    }
    if (
      error instanceof YoutubeTranscriptNotAvailableError ||
      error instanceof YoutubeTranscriptVideoUnavailableError
    ) {
      throw new TranscriptRetryableError();
    }
    throw error;
  }
}
