import { beforeEach, describe, expect, mock, test } from "bun:test";
import type { TranscriptConfig } from "youtube-transcript-plus";
import {
  YoutubeTranscriptDisabledError,
  YoutubeTranscriptNotAvailableError,
  YoutubeTranscriptTooManyRequestError,
} from "youtube-transcript-plus";

const listLanguages = mock(async () => [] as Array<{
  languageCode: string;
  languageName?: string;
  isAutoGenerated: boolean;
}>);

const fetchTranscript = mock(async (_videoId: string, _options?: TranscriptConfig) => ({
  segments: [] as Array<{ text: string; offset: number; duration: number }>,
}));

mock.module("youtube-transcript-plus", () => ({
  fetchTranscript,
  listLanguages,
  YoutubeTranscriptDisabledError,
  YoutubeTranscriptNotAvailableError,
  YoutubeTranscriptTooManyRequestError,
  YoutubeTranscriptVideoUnavailableError: class YoutubeTranscriptVideoUnavailableError extends Error {},
}));

const cacheGet = mock(async () => null as null | { response?: { video_id: string; language: string; transcript: unknown[] } });

const cacheSave = mock(async () => undefined);

const markUnavailable = mock(async () => undefined);

const getByVideoId = mock(async () => [] as unknown[]);

const upsertSegments = mock(async () => undefined);

mock.module("@/lib/db/repository", () => ({
  TranscriptCacheRepository: {
    get: cacheGet,
    saveResponse: cacheSave,
    markUnavailable,
  },
  TranscriptRepository: {
    getByVideoId,
    upsertSegments,
  },
}));

const { fetchTranscriptResponse, TranscriptRetryableError } = await import("./transcript-api");

const VIDEO_ID = "dQw4w9WgXcQ";

beforeEach(() => {
  listLanguages.mockReset();
  fetchTranscript.mockReset();
  cacheGet.mockReset();
  cacheSave.mockReset();
  markUnavailable.mockReset();
  getByVideoId.mockReset();
  upsertSegments.mockReset();
  cacheGet.mockResolvedValue(null);
  getByVideoId.mockResolvedValue([]);
});

describe("fetchTranscriptResponse", () => {
  test("maps offset to start in seconds", async () => {
    listLanguages.mockResolvedValue([
      { languageCode: "en", isAutoGenerated: false },
    ]);
    fetchTranscript.mockResolvedValue({
      segments: [{ text: "Hello", offset: 1.5, duration: 2 }],
    });

    const result = await fetchTranscriptResponse(VIDEO_ID);

    expect(result.transcript).toEqual([{ text: "Hello", start: 1.5, duration: 2 }]);
    expect(fetchTranscript).toHaveBeenCalledWith(
      VIDEO_ID,
      expect.objectContaining({ lang: "en", retries: 3, retryDelay: 1000 }),
    );
  });

  test("prefers human id over ASR en", async () => {
    listLanguages.mockResolvedValue([
      { languageCode: "en", isAutoGenerated: true },
      { languageCode: "id", isAutoGenerated: false },
    ]);
    fetchTranscript.mockResolvedValue({
      segments: [{ text: "Halo", offset: 0, duration: 1 }],
    });

    const result = await fetchTranscriptResponse(VIDEO_ID, { language: "id" });

    expect(result.language).toBe("id");
    expect(fetchTranscript).toHaveBeenCalledWith(
      VIDEO_ID,
      expect.objectContaining({ lang: "id" }),
    );
    expect(fetchTranscript.mock.calls[0]?.[1]?.lang).not.toBe("asr");
    expect(String(fetchTranscript.mock.calls[0]?.[1]?.lang)).not.toContain(",");
  });

  test("passes full languageCode for prefix match", async () => {
    listLanguages.mockResolvedValue([
      { languageCode: "id-ID", isAutoGenerated: false },
    ]);
    fetchTranscript.mockResolvedValue({
      segments: [{ text: "Halo", offset: 0, duration: 1 }],
    });

    await fetchTranscriptResponse(VIDEO_ID, { language: "id" });

    expect(fetchTranscript).toHaveBeenCalledWith(
      VIDEO_ID,
      expect.objectContaining({ lang: "id-ID" }),
    );
  });

  test("returns cache without calling plus", async () => {
    cacheGet.mockResolvedValue({
      response: {
        video_id: VIDEO_ID,
        language: "en",
        transcript: [{ text: "Cached", start: 0, duration: 1 }],
      },
    });

    const result = await fetchTranscriptResponse(VIDEO_ID, { language: "id" });

    expect(result.transcript[0].text).toBe("Cached");
    expect(listLanguages).not.toHaveBeenCalled();
    expect(fetchTranscript).not.toHaveBeenCalled();
  });

  test("does not mark unavailable on too-many-requests", async () => {
    listLanguages.mockRejectedValue(new YoutubeTranscriptTooManyRequestError());

    await expect(fetchTranscriptResponse(VIDEO_ID)).rejects.toBeInstanceOf(
      TranscriptRetryableError,
    );
    expect(markUnavailable).not.toHaveBeenCalled();
    await expect(fetchTranscriptResponse(VIDEO_ID)).rejects.toThrow(
      /temporarily unavailable/i,
    );
  });

  test("marks unavailable on disabled captions", async () => {
    listLanguages.mockRejectedValue(new YoutubeTranscriptDisabledError("off"));

    await expect(fetchTranscriptResponse(VIDEO_ID)).rejects.toThrow(
      /Transcript not available/i,
    );
    expect(markUnavailable).toHaveBeenCalledWith(VIDEO_ID);
  });

  test("does not mark unavailable when NotAvailable follows existing tracks", async () => {
    listLanguages.mockResolvedValue([
      { languageCode: "en", isAutoGenerated: false },
    ]);
    fetchTranscript.mockRejectedValue(new YoutubeTranscriptNotAvailableError("empty"));

    await expect(fetchTranscriptResponse(VIDEO_ID)).rejects.toBeInstanceOf(
      TranscriptRetryableError,
    );
    expect(markUnavailable).not.toHaveBeenCalled();
  });

  test("decodes numeric HTML entities", async () => {
    listLanguages.mockResolvedValue([
      { languageCode: "en", isAutoGenerated: false },
    ]);
    fetchTranscript.mockResolvedValue({
      segments: [{ text: "It&#39;s good", offset: 0, duration: 1 }],
    });

    const result = await fetchTranscriptResponse(VIDEO_ID);
    expect(result.transcript[0].text).toBe("It's good");
  });
});
