services:
  web:
    image: ghcr.io/ahmadrosid/vidiopintar.com:main-b929f6a
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    restart: always
