version: '3.8'

services:
  db-backup:
    build:
      context: ..
      dockerfile: backup/Dockerfile.backup
    container_name: vidiopintar-db-backup
    network_mode: host
    env_file:
      - ../.env
    volumes:
      - ./data:/app/backup/data
      - ../.env:/app/.env:ro
    profiles:
      - backup

  # PostgreSQL 17 instance for local development/testing
  postgres:
    image: postgres:17-alpine
    container_name: vidiopintar-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backup-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  backup-network:
    driver: bridge