import {
  fetchTranscript,
  listLanguages,
  YoutubeTranscriptDisabledError,
  YoutubeTranscriptNotAvailableError,
  YoutubeTranscriptTooManyRequestError,
  YoutubeTranscriptVideoUnavailableError,
  type CaptionTrackInfo,
  type TranscriptSegment,
  type VideoDetails,
} from "youtube-transcript-plus";

const PLUS_FETCH_OPTIONS = { retries: 3, retryDelay: 1000 } as const;

function decodeHtmlEntities(text: string): string {
  const named: Record<string, string> = {
    "&amp;": "&",
    "&lt;": "<",
    "&gt;": ">",
    "&quot;": '"',
    "&apos;": "'",
    "&#39;": "'",
    "&nbsp;": " ",
  };
  const once = (value: string) =>
    value
      .replace(/&(?:amp|lt|gt|quot|apos|nbsp|#39);/g, (match) => named[match] ?? match)
      .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(parseInt(code, 10)))
      .replace(/&#x([0-9a-fA-F]+);/g, (_, code) => String.fromCharCode(parseInt(code, 16)));

  let decoded = text;
  let prev = "";
  while (prev !== decoded) {
    prev = decoded;
    decoded = once(decoded);
  }
  return decoded;
}

export function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&\n?#]+)/,
    /youtube\.com\/watch\?.*v=([^&\n?#]+)/,
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }

  if (/^[a-zA-Z0-9_-]{11}$/.test(url)) {
    return url;
  }

  return null;
}

function matchesLanguagePrefix(languageCode: string, prefix: string): boolean {
  const code = languageCode.toLowerCase();
  const needle = prefix.toLowerCase();
  return code === needle || code.startsWith(`${needle}-`);
}

function pickCaptionTrack(
  tracks: CaptionTrackInfo[],
  preferred = "en",
): CaptionTrackInfo | null {
  if (tracks.length === 0) {
    return null;
  }

  const preferredCode = preferred.trim().toLowerCase();
  const fallbacks = ["en", "id"].filter((code) => code !== preferredCode);

  const humanPreferred = tracks.find(
    (track) => !track.isAutoGenerated && matchesLanguagePrefix(track.languageCode, preferredCode),
  );
  if (humanPreferred) {
    return humanPreferred;
  }

  const asrPreferred = tracks.find(
    (track) => track.isAutoGenerated && matchesLanguagePrefix(track.languageCode, preferredCode),
  );
  if (asrPreferred) {
    return asrPreferred;
  }

  for (const code of fallbacks) {
    const human = tracks.find(
      (track) => !track.isAutoGenerated && matchesLanguagePrefix(track.languageCode, code),
    );
    if (human) {
      return human;
    }
  }

  return tracks.find((track) => track.isAutoGenerated) ?? null;
}

function joinTranscript(segments: TranscriptSegment[]): string {
  return segments
    .map((item) => decodeHtmlEntities(item.text))
    .filter((text) => text && text !== "N/A")
    .join(" ");
}

async function fetchTranscriptSegments(videoId: string, sendMetadata: boolean) {
  let tracks: CaptionTrackInfo[];
  try {
    tracks = await listLanguages(videoId, PLUS_FETCH_OPTIONS);
  } catch (error) {
    if (
      error instanceof YoutubeTranscriptDisabledError ||
      error instanceof YoutubeTranscriptNotAvailableError
    ) {
      throw new Error("No transcript available for this video. The video may not have captions enabled.");
    }
    if (
      error instanceof YoutubeTranscriptTooManyRequestError ||
      error instanceof YoutubeTranscriptVideoUnavailableError
    ) {
      throw new Error("Transcript temporarily unavailable. Try again later.");
    }
    throw error;
  }

  const track = pickCaptionTrack(tracks, "en");
  if (!track) {
    throw new Error("No transcript available for this video. The video may not have captions enabled.");
  }

  const fetched = await fetchTranscript(videoId, {
    ...PLUS_FETCH_OPTIONS,
    lang: track.languageCode,
    videoDetails: sendMetadata,
  });

  const segments = Array.isArray(fetched) ? fetched : fetched.segments;
  const transcript = joinTranscript(segments);
  if (!transcript.trim()) {
    throw new Error("Transcript is empty or contains no valid content.");
  }

  const title = Array.isArray(fetched) ? undefined : (fetched.videoDetails as VideoDetails | undefined)?.title;
  return { transcript, title };
}

export async function fetchYoutubeTranscript(videoUrlOrId: string): Promise<string> {
  const videoId = extractVideoId(videoUrlOrId);
  if (!videoId) {
    throw new Error(`Invalid YouTube URL or video ID: ${videoUrlOrId}`);
  }

  const { transcript } = await fetchTranscriptSegments(videoId, false);
  return transcript;
}

export async function fetchYoutubeTranscriptWithMetadata(videoUrlOrId: string): Promise<{
  transcript: string;
  title?: string;
}> {
  const videoId = extractVideoId(videoUrlOrId);
  if (!videoId) {
    throw new Error(`Invalid YouTube URL or video ID: ${videoUrlOrId}`);
  }

  return fetchTranscriptSegments(videoId, true);
}
