import { beforeEach, describe, expect, mock, test } from "bun:test";

const listLanguages = mock(async () => [] as Array<{ languageCode: string; isAutoGenerated: boolean }>);
const fetchTranscript = mock(async () => [] as unknown[]);

mock.module("youtube-transcript-plus", () => ({
  fetchTranscript,
  listLanguages,
  YoutubeTranscriptDisabledError: class YoutubeTranscriptDisabledError extends Error {},
  YoutubeTranscriptNotAvailableError: class YoutubeTranscriptNotAvailableError extends Error {},
  YoutubeTranscriptTooManyRequestError: class YoutubeTranscriptTooManyRequestError extends Error {},
  YoutubeTranscriptVideoUnavailableError: class YoutubeTranscriptVideoUnavailableError extends Error {},
}));

const { extractVideoId, fetchYoutubeTranscript, fetchYoutubeTranscriptWithMetadata } =
  await import("./youtubeTranscript");

beforeEach(() => {
  listLanguages.mockReset();
  fetchTranscript.mockReset();
  delete process.env.TRANSCRIPT_API_KEY;
});

describe("fetchYoutubeTranscript", () => {
  test("succeeds without TRANSCRIPT_API_KEY", async () => {
    listLanguages.mockResolvedValue([{ languageCode: "en", isAutoGenerated: false }]);
    fetchTranscript.mockResolvedValue([{ text: "Hello", offset: 0, duration: 1 }]);

    const text = await fetchYoutubeTranscript("dQw4w9WgXcQ");
    expect(text).toBe("Hello");
    expect(process.env.TRANSCRIPT_API_KEY).toBeUndefined();
  });

  test("throws on invalid URL without calling plus", async () => {
    await expect(fetchYoutubeTranscript("https://example.com")).rejects.toThrow(
      /Invalid YouTube URL/,
    );
    expect(listLanguages).not.toHaveBeenCalled();
  });

  test("throws when joined text is empty", async () => {
    listLanguages.mockResolvedValue([{ languageCode: "en", isAutoGenerated: false }]);
    fetchTranscript.mockResolvedValue([{ text: "N/A", offset: 0, duration: 1 }]);

    await expect(fetchYoutubeTranscript("dQw4w9WgXcQ")).rejects.toThrow(/empty/i);
  });

  test("returns title from videoDetails", async () => {
    listLanguages.mockResolvedValue([{ languageCode: "en", isAutoGenerated: false }]);
    fetchTranscript.mockResolvedValue({
      segments: [{ text: "Hello", offset: 0, duration: 1 }],
      videoDetails: { title: "Never Gonna Give You Up" },
    });

    const result = await fetchYoutubeTranscriptWithMetadata("dQw4w9WgXcQ");
    expect(result.transcript).toBe("Hello");
    expect(result.title).toBe("Never Gonna Give You Up");
  });
});

describe("extractVideoId", () => {
  test("accepts a bare video id", () => {
    expect(extractVideoId("dQw4w9WgXcQ")).toBe("dQw4w9WgXcQ");
  });
});
