name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ahmadrosid
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Create .env file
        run: echo "${{ secrets.ENV_RAW }}" > .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
            context: .
            file: ./deployment/Dockerfile
            push: true
            tags: ghcr.io/${{ github.repository }}:latest
            cache-from: type=gha
            cache-to: type=gha,mode=max

      - name: VPS install ssh keys
        # check this thread to understand why its needed:
        # https://stackoverflow.com/a/70447517
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H vidiopintar.com > ~/.ssh/known_hosts
      - name: Connect, pull and deploy
        run: ssh root@vidiopintar.com "cd /root/vidiopintar.com && git checkout main && git pull origin main && bash ./deployment/deploy.sh && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
